name: Test Echec CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Etape qui echoue volontairement
        run: |
          echo "Simulation d'une erreur de build"
          exit 1
